localgov_base.settings:
  type: config_object
  label: 'LocalGov Base settings'
  mapping:
    localgov_base_remove_css:
      type: boolean
      label: 'Remove CSS libraries from base theme.'
    localgov_base_remove_js:
      type: boolean
      label: 'Remove JS libraries from base theme.'
    localgov_base_remove_unpublished_background_colour:
      type: boolean
      label: 'Remove pink background from unpublished content.'
    localgov_base_add_draft_note_to_unpublished_content:
      type: boolean
      label: 'Add "Draft" to title of unpublished content.'
